Update Jobe dockerfile to match current JobeInABox
RunestoneInteractive/rs pull request #569
Opened 2024-11-06 21:07 UTC by ascholerChemeketa

Not needed, but seems worthwhile to update dockerfile while updating Jobe itself.

2024-11-06 21:19 UTC, bnmnetp commented on projects/jobe/Dockerfile
> -    catch2 \
Do we want to keep this for backward compatibility?  I think we do.

2024-11-06 21:21 UTC, bnmnetp requested changes

2024-11-06 21:21 UTC, bnmnetp commented on projects/jobe/Dockerfile
> -    python3 -m pip install pylint beautifulsoup4 pandas requests altair && \
definitely need to keep these as some books rely on them.

2024-11-06 21:21 UTC, bnmnetp commented on projects/jobe/Dockerfile
> -ARG TZ=Etc/GMT-0
I think we want to be in GMT so jobe is in the same timezone as the rest of the servers

2024-11-06 21:21 UTC, bnmnetp commented on projects/jobe/Dockerfile
> -    openjdk-18-jdk \
I wonder which version of java we end up with if we use default-jdk???  This could be bad for CSAwesome.

2024-11-07 19:02 UTC, closed without merging

2024-11-07 19:02 UTC, ascholerChemeketa commented
Sorry, that was a sloppy end of the day job.

Started a clean redo and am not 100% sure we want the API keys or other changes. Leaving well-enough alone until if/when we go to jobe 2.x