RUN-20/RUN-25 Autoupdate assignment points when adding or removing exercise/The assignment type of Regular should be selected by default
RunestoneInteractive/rs pull request #619
Opened 2024-12-31 09:56 UTC by morozov-av

2025-01-02 22:15 UTC, bnmnetp requested changes
Just one minor change...

2025-01-02 22:15 UTC, bnmnetp commented on components/rsptx/db/models.py
> +class UpdateAssignmentExercisesPayload(BaseModel):
If we are not generating the schema from a sqlalchemy model, then then it should go in the schemas.py file not here.

2025-01-02 22:15 UTC, bnmnetp commented on bases/rsptx/assignment_server_api/routers/instructor.py
> +def instructor_role_required():
Once I merge this, I'll move these new decorators to a new component in components/rsptx/validator so that we can import them and use them for many more endpoints.

2025-01-02 22:15 UTC, bnmnetp commented on bases/rsptx/assignment_server_api/assignment_builder/src/renderers/assignment.jsx
> +function handleChange() {
Interesting....  I always felt that there must be a better way to achieve this...maybe something we can talk about later.

2025-01-02 22:15 UTC, bnmnetp commented on bases/rsptx/assignment_server_api/routers/instructor.py
> +            # Continue execution of the original function
Some functions will require the user for more than just instructor validation.  Maybe we want to inject it into kwargs if the "user" key is already there?  Or maybe the regular dependency injection will work fine.

Not a worry for this PR, but something I want to think about.  Especially if this is used on an endpoint that returns a page, the dependency injection ends up redirecting to the appropriate login page.  which this may also do...

2025-01-09 15:01 UTC, morozov-av commented on bases/rsptx/assignment_server_api/assignment_builder/src/renderers/assignment.jsx
> +function handleChange() {
Of course! This code is not used in the new version of our pages, only for the old ones. I just uncommented it :)
We will remove it along with the removal of all the old pages for the Assignment Builder.

2025-01-09 15:05 UTC, morozov-av commented on bases/rsptx/assignment_server_api/routers/instructor.py
> +            # Continue execution of the original function
At the moment, it's hard for me to either agree or disagree with you :) I just noticed that we duplicate the code for this check quite often, and I thought it would be interesting to move it into a separate decorator. I'd be happy to improve it, but let's not do it as part of this PR :)

2025-01-09 15:10 UTC, morozov-av commented on components/rsptx/db/models.py
> +class UpdateAssignmentExercisesPayload(BaseModel):
Thanks! Fixed

2025-01-09 21:00 UTC, bnmnetp approved these changes

2025-01-09 21:02 UTC, merged